apiVersion: v1
kind: Service
metadata:
  name: trading-agent-core
  labels:
    app: trading-agent
    component: core
spec:
  selector:
    app: trading-agent
    component: core
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  - port: 8081
    targetPort: 8081
    name: metrics
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: data-service
  labels:
    app: trading-agent
    component: data-service
spec:
  selector:
    app: trading-agent
    component: data-service
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: execution-service
  labels:
    app: trading-agent
    component: execution-service
spec:
  selector:
    app: trading-agent
    component: execution-service
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: sentiment-analyzer
  labels:
    app: trading-agent
    component: sentiment-analyzer
spec:
  selector:
    app: trading-agent
    component: sentiment-analyzer
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: trading-api
  labels:
    app: trading-agent
    component: api
spec:
  selector:
    app: trading-agent
    component: api
  ports:
  - port: 80
    targetPort: 8080
    name: http
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: trading-dashboard
  labels:
    app: trading-agent
    component: dashboard
spec:
  selector:
    app: trading-agent
    component: dashboard
  ports:
  - port: 80
    targetPort: 80
    name: http
  type: LoadBalancer
