global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'market-data-processor'
    static_configs:
      - targets: ['market-data-processor:8080']
    
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
