# Sentiment Analysis System Deployment Configuration
# Environment: Development

# LLM Configuration
llm:
  primary_model: "gpt-4o"
  financial_model: "gpt-4o"
  batch_size: 5
  use_cached_responses: true
  cache_ttl: 3600
  max_concurrent_requests: 10
  request_timeout: 60

# Sentiment Analysis Configuration
sentiment_analysis:
  enabled: true
  consensus_system:
    enabled: true
    weights:
      llm: 0.40
      news: 0.20
      social_media: 0.20
      market: 0.10
      onchain: 0.10
    adaptive_weights: true
    performance_tracking: true
    tracking_window: 720  # 12 hours
    confidence_threshold: 0.65
    update_interval: 300  # 5 minutes

# Early Detection Configuration
early_detection:
  enabled: true
  realtime_detector:
    enabled: true
    refresh_interval: 300  # 5 minutes
    source_weights:
      twitter: 0.3
      news: 0.4
      reddit: 0.2
      alerts: 0.1
    minimum_score_threshold: 0.65
    max_events_per_hour: 10
    batch_size: 20
    deduplication_window: 1800  # 30 minutes
  sentiment_integration:
    enabled: true
    bidirectional: true
    event_impact_threshold: 0.7

# Dashboard Configuration
dashboard:
  llm_event_dashboard:
    enabled: true
    port: 8051
    max_display_items: 50
    update_interval: 30
    theme: "light"
    charts:
      sentiment_trend: true
      confidence_distribution: true
      event_timeline: true
      model_performance: true
    debug_mode: true