apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: ai-trading
  labels:
    app: api
    tier: backend
    version: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
      version: canary
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: api
        tier: backend
        version: canary
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8000"
    spec:
      containers:
      - name: api
        image: ${DOCKER_REGISTRY}/ai-trading-agent/api:canary
        imagePullPolicy: Always
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: url
          - name: REDIS_URL
            valueFrom:
              secretKeyRef:
                name: redis-credentials
                key: url
          - name: JWT_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: api-credentials
                key: jwt_secret
          - name: JWT_ALGORITHM
            value: "HS256"
          - name: ACCESS_TOKEN_EXPIRE_MINUTES
            value: "120"
          - name: LOG_LEVEL
            value: "DEBUG"
          - name: CANARY
            value: "true"
          - name: SECURITY_AUDIT_ENABLED
            value: "true"
          - name: ENV
            value: "production"
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        ports:
          - containerPort: 8000
            name: http
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: api-canary
  namespace: ai-trading
  labels:
    app: api
    version: canary
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: api
    version: canary
