coverage:
  status:
    project:
      default:
        # Overall project threshold
        target: 80%
        threshold: 1%
      detection:
        # Market regime detection components
        target: 85%
        paths:
          - "src/ml/detection/**"
        flags:
          - detection
        # Only notify on significant changes (1% for critical components)
        threshold: 1%
      models:
        # ML models components
        target: 80%
        paths:
          - "src/ml/models/**"
        flags:
          - models
        # Only notify on significant changes (1.5% for model components)
        threshold: 1.5%
      evaluation:
        # Evaluation components
        target: 75%
        paths:
          - "src/ml/evaluation/**"
        flags:
          - evaluation
        # Only notify on significant changes (2% for evaluation components)
        threshold: 2%
      rust:
        # Performance-critical Rust components
        target: 80%
        flags:
          - rust
        # Only notify on significant changes (1% for performance-critical components)
        threshold: 1%
      dashboard:
        # React/TypeScript dashboard
        target: 80%
        paths:
          - "dashboard/**"
        flags:
          - dashboard
        # Only notify on significant changes (2% for dashboard components)
        threshold: 2%

    patch:
      default:
        # Ensure new code meets minimum coverage
        target: 80%
        threshold: 2%
      detection:
        target: 85%
        flags:
          - detection
        # Stricter threshold for critical detection components
        threshold: 1%
      models:
        target: 80%
        flags:
          - models
        # Standard threshold for model components
        threshold: 1.5%

  notify:
    after_n_builds: 3
    require_changes: true
    wait_for_ci: true
    # Only notify when coverage changes significantly
    if_not_found: success
    if_ci_failed: error
    if_no_uploads: error

flags:
  detection:
    paths:
      - src/ml/detection
    carryforward: true
  models:
    paths:
      - src/ml/models
    carryforward: true
  evaluation:
    paths:
      - src/ml/evaluation
    carryforward: true
  rust:
    paths:
      - rust
    carryforward: true
  dashboard:
    paths:
      - dashboard
    carryforward: true

ignore:
  - "tests/**/*"
  - "**/__init__.py"
  - "docs/**/*"
  - "**/setup.py"

comment:
  # PR comment behavior
  behavior: default
  require_changes: true
  require_base: true
  require_head: true
  show_carryforward_flags: true
  hide_project_coverage: false
  after_n_builds: 3
  
  # Custom layout focusing on component changes
  layout: "header, diff, components, files"
  
  # Component-specific sections in comments
  show_components: true
  components:
    - name: "Market Regime Detection"
      paths:
        - "src/ml/detection/**"
      target: 85%
      # Only highlight significant changes (1% for critical components)
      threshold: 1%
    - name: "ML Models"
      paths:
        - "src/ml/models/**"
      target: 80%
      # Only highlight significant changes (1.5% for model components)
      threshold: 1.5%
    - name: "Performance Evaluation"
      paths:
        - "src/ml/evaluation/**"
      target: 75%
      # Only highlight significant changes (2% for evaluation components)
      threshold: 2%
    - name: "Rust Core"
      paths:
        - "rust/**"
      target: 80%
      # Only highlight significant changes (1% for performance-critical components)
      threshold: 1%
    - name: "Dashboard"
      paths:
        - "dashboard/**"
      target: 80%
      # Only highlight significant changes (2% for dashboard components)
      threshold: 2%

  # Detailed change information
  show_critical_files: true
  critical_files:
    - "src/ml/detection/regime_detector.py"
    - "src/ml/models/adaptive_model.py"
    - "rust/src/performance.rs"
  
  # Component-specific warnings
  warnings:
    - "detection coverage decreased"
    - "models coverage below 80%"
    - "rust performance critical coverage decreased"
