version: '3'

services:
  trading-engine:
    build:
      context: .
      dockerfile: Dockerfile.trading-engine
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./config:/app/config
      - ./logs:/app/logs
    environment:
      - MEXC_API_KEY=${MEXC_API_KEY}
      - MEXC_API_SECRET=${MEXC_API_SECRET}
    restart: unless-stopped

  visualization:
    build:
      context: .
      dockerfile: Dockerfile.visualization
    ports:
      - "5002:5002"
    depends_on:
      - trading-engine
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  monitoring:
    build:
      context: .
      dockerfile: Dockerfile.monitoring
    ports:
      - "5001:5001"
    depends_on:
      - trading-engine
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

networks:
  default:
    driver: bridge
