[package]
name = "rust_test_extension"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_test_extension"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22.1", features = ["extension-module"] }
