[package]
name = "rust_backtesting_extension"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_backtesting_extension"
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ta = "0.5.0"
