# AI Trading Agent - Agent Configuration Template
# This file defines the configuration for the agent architecture components

# Data Management Configuration
data_manager:
  type: "SimpleDataManager"  # Options: SimpleDataManager, CustomDataManager
  config:
    data_dir: "data/"
    timeframe: "1d"
    data_types: ["ohlcv", "sentiment"]
    # For live data
    use_live_data: false
    api_key: "${MARKET_DATA_API_KEY}"  # Environment variable reference

# Strategy Configuration
strategy:
  type: "SentimentStrategy"  # Options: SentimentStrategy, CustomStrategy
  config:
    name: "SentimentBasedTrading"
    sentiment_threshold: 0.3
    position_size_pct: 0.1
    symbols: ["BTC/USD", "ETH/USD", "ADA/USD"]

# Risk Management Configuration
risk_manager:
  type: "SimpleRiskManager"  # Options: SimpleRiskManager, CustomRiskManager
  config:
    max_position_size: null  # null means no limit
    max_portfolio_risk_pct: 0.05
    stop_loss_pct: 0.05
    max_drawdown_pct: 0.15
    correlation_limit: 0.7

# Portfolio Management Configuration
portfolio_manager:
  type: "PortfolioManager"  # Options: PortfolioManager, CustomPortfolioManager
  config:
    initial_capital: 100000.0
    risk_per_trade: 0.02
    max_position_size: 0.2
    max_correlation: 0.7
    rebalance_frequency: "weekly"  # Options: daily, weekly, monthly

# Execution Handler Configuration
execution_handler:
  type: "SimulatedExecutionHandler"  # Options: SimulatedExecutionHandler, LiveExecutionHandler
  config:
    commission_rate: 0.001
    slippage_pct: 0.001
    slippage_model: "fixed"  # Options: fixed, normal, proportional
    allow_partial_fills: true
    simulate_rejections: false

# Backtest Configuration
backtest:
  start_date: "2020-01-01"
  end_date: "2020-12-31"
  symbols: ["BTC/USD", "ETH/USD", "ADA/USD"]
  initial_capital: 100000.0
  
  # Performance metrics to calculate
  metrics:
    - total_return
    - sharpe_ratio
    - sortino_ratio
    - max_drawdown
    - win_rate
    - profit_factor
    - calmar_ratio
    - omega_ratio
  
  # Rust acceleration options
  use_rust: true  # Set to true to use Rust-accelerated components if available
  rust_options:
    parallel: true  # Use parallel processing in Rust
    optimization_level: 3  # Optimization level (1-3)
    precision: "double"  # Floating-point precision (float, double)

# Logging Configuration
logging:
  level: "INFO"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
  log_to_file: true
  log_file: "logs/agent.log"
  log_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Custom Components Configuration
# Use this section to register custom components
custom_components:
  # Example:
  # - type: "data_manager"
  #   name: "MyCustomDataManager"
  #   module_path: "my_project.data_managers"
  #   class_name: "MyCustomDataManager"
