# Analysis agents configuration

# Global settings
analysis_agents:
  enabled: true
  enabled_agents:
    - technical_indicators
    - pattern_recognition
    - sentiment_analysis
    # Add more agents as they are implemented

  # Technical indicators agent configuration
  technical_indicators:
    enabled: true
    class_name: TechnicalIndicatorAgent
    module: src.analysis_agents.technical_indicators
    analysis_interval: 60  # Seconds between analysis runs
    max_cache_size: 500   # Maximum number of candles to keep in cache
    
    # By default, analyze all symbols and exchanges
    # Uncomment and modify to specify specific symbols or exchanges
    # symbols:
    #   - BTC/USDT
    #   - ETH/USDT
    # exchanges:
    #   - binance
    
    # Timeframes to analyze
    timeframes:
      - 1m
      - 5m
      - 15m
      - 1h
      - 4h
      - 1d
    
    # Indicators to calculate
    indicators:
      - SMA
      - EMA
      - RSI
      - MACD
      - BBANDS
    
    # Indicator-specific parameters
    parameters:
      SMA:
        periods: [20, 50, 200]
      
      EMA:
        periods: [9, 12, 26, 50, 200]
      
      RSI:
        period: 14
      
      MACD:
        fast_period: 12
        slow_period: 26
        signal_period: 9
      
      BBANDS:
        period: 20
        nbdevup: 2
        nbdevdn: 2
        
  # Pattern Recognition agent configuration
  pattern_recognition:
    enabled: true
    class_name: PatternRecognitionAgent
    module: src.analysis_agents.pattern_recognition
    analysis_interval: 60  # Seconds between analysis runs
    max_cache_size: 500    # Maximum number of candles to keep in cache
    min_candles: 50       # Minimum candles needed for pattern detection
    min_pattern_quality: 75.0  # Minimum pattern quality threshold (0-100)
    require_volume_confirmation: true
    
    # By default, analyze all symbols and exchanges
    # symbols:
    #   - BTC/USDT
    #   - ETH/USDT
    # exchanges:
    #   - binance
    
    # Timeframes to analyze
    timeframes:
      - 15m
      - 1h
      - 4h
      - 1d
    
    # Pattern categories to detect
    pattern_categories:
      - reversal
      - continuation
      - candlestick
    
    # Patterns configuration
    patterns:
      reversal:
        enabled: true
        types: ["HeadAndShoulders", "InverseHeadAndShoulders", "DoubleTop", "DoubleBottom"]
        min_formation_bars: 15
      
      continuation:
        enabled: true
        types: ["Flag", "Pennant", "Triangle"]
        min_formation_bars: 7
      
      candlestick:
        enabled: true
        types: ["Engulfing", "Hammer", "ShootingStar"]
        
  # Sentiment Analysis agent configuration
  sentiment_analysis:
    enabled: true
    class_name: SentimentAnalysisAgent
    module: src.analysis_agents.sentiment_analysis
    analysis_interval: 60  # Seconds between analysis runs
    max_history_size: 100  # Maximum number of sentiment records to keep
    min_confidence: 0.7
    sentiment_shift_threshold: 0.15  # Minimum change to publish a new sentiment event
    contrarian_threshold: 0.8  # Threshold for extreme sentiment (contrarian signals)
    
    # By default, analyze all symbols and exchanges
    # symbols:
    #   - BTC/USDT
    #   - ETH/USDT
    # exchanges:
    #   - binance
    
    # Timeframes to analyze
    timeframes:
      - 1h
      - 4h
      - 1d
    
    # Data sources configuration
    sources:
      social_media:
        enabled: true
        platforms: ["Twitter", "Reddit"]
        interval_seconds: 300  # 5 minutes
      
      news:
        enabled: true
        sources: ["CryptoNews", "CoinDesk", "CoinTelegraph"]
        interval_seconds: 600  # 10 minutes
      
      market_sentiment:
        enabled: true
        indicators: ["FearGreedIndex", "LongShortRatio"]
        interval_seconds: 3600  # 1 hour
      
      onchain:
        enabled: true
        metrics: ["LargeTransactions", "ActiveAddresses", "NetworkHashRate"]
        interval_seconds: 3600  # 1 hour
