# AI Trading Agent Configuration

# System settings
system:
  name: "AI Trading Agent"
  version: "2.0.0"
  log_level: "INFO"
  log_file: "logs/trading_agent.log"
  timezone: "UTC"

# Data sources configuration
data_sources:
  active_provider: ccxt # Options: mock, ccxt, yfinance (when added)

  # Mock Provider Settings
  mock:
    generation_seed: 42 # Example specific setting for mock

  # CCXT Provider Settings
  ccxt:
    exchange_id: binance # Default exchange (e.g., binance, kraken, kucoin, bybit)
    api_key: null       # Optional: Set via .env or leave null for public endpoints
    secret_key: null    # Optional: Set via .env or leave null for public endpoints
    password: null      # Optional: For exchanges like KuCoin, set via .env
    fetch_limit: 1000   # Max candles per historical data request
    options:            # Custom CCXT exchange options (optional)
      # defaultType: 'future' # Example: uncomment to default to futures markets
      # adjustForTimeDifference: True

  # YFinance Provider Settings (Example for later)
  # yfinance:

# Dashboard settings
dashboard:
  host: "127.0.0.1"
  port: 8050
  debug: true
  theme: "dark"  # Options: light, dark
  title: "AI Trading Agent Dashboard"

# Sentiment analysis settings
sentiment:
  enabled: true
  use_mock: true  # Use mock sentiment data
  sources: ["twitter", "reddit", "news", "fear_greed"]
  update_interval_minutes: 30

# Trading settings (to be expanded in future phases)
trading:
  mode: "backtest"  # Options: backtest, paper, live
  default_strategy: "sentiment_basic"
  risk_per_trade_pct: 1.0
