# Data Collection Configuration

data_collection:
  # Enable/disable data collection
  enabled: true
  
  # List of enabled exchanges
  enabled_exchanges:
    - binance
    # Uncomment to enable additional exchanges as they are implemented
    # - coinbase
    # - kraken
    # - ftx
  
  # General settings
  general:
    history_backfill: true  # Whether to backfill historical data on startup
    backfill_days: 7        # Number of days to backfill
    reconnect_attempts: 3   # Number of attempts to reconnect to an exchange
    reconnect_delay: 5      # Delay between reconnect attempts (seconds)
  
  # Symbol discovery settings
  symbol_discovery:
    enabled: true           # Whether to discover available symbols
    refresh_interval: 3600  # How often to refresh symbols (seconds)
    min_volume_filter: 1000000  # Min 24h volume to include a symbol (in USD)
    
  # Data persistence settings
  persistence:
    enabled: true             # Whether to persist collected data
    storage_type: "file"      # Options: "file", "database"
    file_format: "csv"        # Options: "csv", "parquet", "json"
    database_connection: ""   # Database connection string (if storage_type is "database")
    
    # Retention settings
    candles:
      enabled: true
      retention_days:
        "1m": 7     # Store 1-minute candles for 7 days
        "5m": 30    # Store 5-minute candles for 30 days
        "15m": 90   # Store 15-minute candles for 90 days
        "1h": 365   # Store 1-hour candles for 365 days
        "4h": 730   # Store 4-hour candles for 730 days
        "1d": 3650  # Store daily candles for 10 years
    
    orderbooks:
      enabled: false  # Orderbook storage is disabled by default as it requires a lot of storage
      snapshot_interval: 60  # How often to store orderbook snapshots (seconds)
      retention_days: 3      # Store orderbooks for 3 days
    
    trades:
      enabled: true
      retention_days: 7  # Store trades for 7 days
  
  binance:
    use_testnet: false
    default_symbols:
      - "BTC/USDT"
      - "ETH/USDT"
      - "BNB/USDT"
      - "SOL/USDT"
      - "XRP/USDT"
    max_requests_per_minute: 1200
    max_requests_per_second: 20
    timeout_seconds: 30
    retry_count: 3
    retry_delay_seconds: 1
    use_websocket: true
    reconnect_max_attempts: 10
    reconnect_timeout_seconds: 5
  
  timeframes:
    available:
      - "1m"
      - "5m"
      - "15m"
      - "30m"
      - "1h"
      - "4h"
      - "1d"
    default: "1h"
    store_all: false
  
  data_validation:
    check_timestamp_sequence: true
    check_price_jumps: true
    max_price_jump_percent: 10
    fill_missing_candles: true
    replace_zeros_with_previous: true
    discard_incomplete_candles: true
  
  storage:
    in_memory_limit_per_symbol_candles: 5000
    use_influxdb: true
    influxdb_measurement: "candles"
    compression_enabled: true
    query_timeout_seconds: 30
    batch_size: 500 