# Decision engine configuration

# Global settings
decision_engine:
  enabled: true
  # Symbols to actively monitor
  monitored_symbols:
    - BTC/USDT
    - ETH/USDT
    - SOL/USDT
    - BNB/USDT
  
  # Decision confidence threshold
  min_confidence: 0.85
  
  # Minimum reward-to-risk ratio
  min_reward_risk_ratio: 2.0
  
  # Sources that must be present for a valid decision
  required_agent_types:
    - technical
    - pattern
  
  # Risk management parameters
  kelly_fraction: 0.4  # Fraction of Kelly criterion to use (conservative)
  max_per_trade_risk: 0.01  # Maximum 1% risk per trade
  max_per_symbol_exposure: 0.05  # Maximum 5% portfolio allocation per symbol
  max_correlated_exposure: 0.15  # Maximum 15% for correlated assets
  
  # Prediction aggregator settings
  aggregator:
    min_confidence: 0.7  # Minimum confidence for individual predictions
    min_agent_agreement: 2  # Minimum number of agents that must agree
    prediction_ttl: 3600  # Prediction time-to-live in seconds
    time_decay_factor: 0.9  # Decay factor for older predictions
    
    # Agent weights by source
    agent_weights:
      technical_indicators: 0.4
      pattern_recognition: 0.4
      sentiment_analysis: 0.2
      
    # Default symbol-specific weights
    symbol_weights:
      # For BTC, weight technical analysis more heavily
      BTC/USDT:
        technical: 0.5
        pattern: 0.3
        sentiment: 0.2
      
      # For ETH, more balanced weights
      ETH/USDT:
        technical: 0.4
        pattern: 0.4
        sentiment: 0.2
  
  # Publication settings
  publication:
    # Throttle similar signals (seconds)
    signal_throttle: 300
    # Include pattern details in signals
    include_pattern_details: true
    # Include technical indicator values in signals
    include_technical_details: true
