# Early Event Detection System Configuration

# General settings
enabled: true
update_interval: 3600  # Update interval in seconds (1 hour)
assets:
  - BTC
  - ETH
  - SOL
  - XRP

# Data collection settings
data_collection:
  social_media:
    platforms:
      - twitter
      - reddit
    twitter:
      keywords:
        - crypto
        - bitcoin
        - ethereum
        - cryptocurrency
        - blockchain
      accounts:
        - elonmusk
        - jimmysong
        - aantonop
        - cz_binance
        - SBF_FTX
    reddit:
      subreddits:
        - cryptocurrency
        - bitcoin
        - ethereum
        - CryptoMarkets
  
  news:
    sources:
      - coindesk
      - cointelegraph
      - theblock
      - decrypt
    keywords:
      - regulation
      - sec
      - fed
      - central bank
      - interest rate
      - inflation
      - monetary policy
      - government
      - ban
      - law
  
  official:
    sources:
      - federal_reserve
      - ecb
      - sec
      - cftc
      - us_treasury
    document_types:
      - press_release
      - statement
      - speech
      - testimony
  
  financial_data:
    types:
      - price
      - volume
      - options
      - futures
    interval: 1h

# Processing settings
processing:
  nlp:
    sentiment_threshold: 0.3
    entity_threshold: 0.5
    keyword_threshold: 0.7
  
  social_media:
    influence_threshold: 0.7
    spread_threshold: 0.6
    engagement_threshold: 0.5
  
  news:
    entity_relevance_threshold: 0.6
    keyword_relevance_threshold: 0.7
    sentiment_threshold: 0.3
  
  financial_data:
    anomaly_threshold: 0.7

# Analysis settings
analysis:
  social_media:
    influence_threshold: 0.7
    spread_threshold: 0.6
    sentiment_threshold: 0.3
  
  news:
    entity_relevance_threshold: 0.6
    keyword_relevance_threshold: 0.7
    sentiment_threshold: 0.3
  
  financial_data:
    anomaly_threshold: 0.7
  
  cross_source:
    correlation_threshold: 0.6

# Signal generation settings
signals:
  confidence_threshold: 0.6
  impact_threshold: 0.5
  expiration:
    immediate: 4   # hours
    short_term: 24 # hours
    medium_term: 72 # hours
    long_term: 168 # hours

# Integration settings
integration:
  enabled: true
  signal_confidence_threshold: 0.7

# Real-time event detection settings
realtime:
  enabled: true
  batch_size: 5
  batch_interval: 60  # Process batches every 60 seconds
  min_confidence: 0.7
  min_severity: 5  # 1-10 scale
  
  # Source credibility scores (0-1)
  source_credibility:
    official: 0.9
    verified_news: 0.8
    financial_data: 0.85
    major_social: 0.7
    community: 0.5
    unverified: 0.3
  
  # Event types to detect (used for filtering)
  event_types:
    - monetary_policy
    - regulation
    - trade_war
    - geopolitical
    - economic_data
    - corporate
    - market
    - technology
    - security

# Sentiment integration settings
sentiment_integration:
  enabled: true
  min_consensus_confidence: 0.85
  min_disagreement_level: 0.3
  
  # Event subscriptions
  event_subscriptions:
    - sentiment_event
    - EarlyEventSignal
    - RealtimeEventDetected