# Exchange Configuration

# Binance Exchange Configuration
exchanges:
  binance:
    connector_class: BinanceConnector
    api_key: ""  # Leave empty if using public API only
    api_secret: ""  # Leave empty if using public API only
    use_testnet: false  # Set to true to use the Binance Testnet
    rate_limit:
      requests_per_minute: 1200  # Binance limit for IP-based rate limiting
      orders_per_second: 5  # Binance limit for order-based rate limiting
    auto_subscribe:
      - symbol: BTC/USDT
        timeframes: ["1m", "5m", "15m", "1h", "4h", "1d"]
        orderbook: true
        trades: true
      - symbol: ETH/USDT
        timeframes: ["1m", "5m", "15m", "1h", "4h", "1d"]
        orderbook: true
        trades: true
      - symbol: BNB/USDT
        timeframes: ["1m", "5m", "15m", "1h"]
        orderbook: false
        trades: false
      - symbol: SOL/USDT
        timeframes: ["1m", "15m", "1h"]
        orderbook: false
        trades: false
      - symbol: XRP/USDT
        timeframes: ["1m", "15m", "1h"]
        orderbook: false
        trades: false

  # Additional exchange configurations can be added here
  # Example for Coinbase Pro:
  # coinbase:
  #   connector_class: CoinbaseConnector
  #   api_key: ""
  #   api_secret: ""
  #   passphrase: ""
  #   rate_limit:
  #     requests_per_second: 3
  #   auto_subscribe:
  #     - symbol: BTC/USD
  #       timeframes: ["1m", "5m", "15m", "1h"]
  #       orderbook: true
  #       trades: true 