# Execution Service Configuration

# General settings
enabled: true
component_id: execution

# Order execution settings
retry_attempts: 3  # Number of attempts for order operations
retry_delay: 1.0  # Delay between retry attempts (seconds)
order_update_interval: 1.0  # Interval for checking order status (seconds)
cancel_orders_on_shutdown: true  # Whether to cancel orders on system shutdown

# Order execution rate limits
max_orders_per_second: 5  # Maximum orders to submit per second
max_order_checks_per_second: 10  # Maximum order status checks per second

# Execution strategies
execution_strategies:
  default:
    type: simple  # simple, twap, iceberg
    timeframe: 60  # Time to complete order (seconds, for time-based strategies)

  twap:  # Time-Weighted Average Price
    type: twap
    timeframe: 300  # 5 minutes
    intervals: 5  # Number of chunks to split the order
    randomize_size: true  # Add randomization to chunk size
    randomize_time: true  # Add randomization to time between chunks

  iceberg:  # Iceberg orders
    type: iceberg
    visible_percent: 0.2  # Percentage of order visible at once
    min_chunk_size: 0.01  # Minimum chunk size (in base currency units)

# Exchange-specific settings
exchange_settings:
  binance:
    default_fee: 0.001  # 0.1% fee
    max_leverage: 20  # Maximum leverage allowed
    precisions:  # Default precisions (can be overridden per symbol)
      price: 2  # Price precision (decimal places)
      amount: 6  # Amount precision (decimal places)

  coinbase:
    default_fee: 0.005  # 0.5% fee
    max_leverage: 5  # Maximum leverage allowed
    precisions:
      price: 2
      amount: 8

# Simulation settings (for testing)
simulation:
  enabled: false
  fill_probability: 0.95  # Probability of an order being filled
  partial_fill_probability: 0.3  # Probability of a partial fill before complete fill
  slippage_max: 0.002  # Maximum slippage (as a percentage of price)
  cancellation_delay: 0.5  # Simulated delay for order cancellation (seconds)

# Logging and monitoring
logging:
  log_all_orders: true  # Whether to log details of all orders
  log_order_updates: true  # Whether to log order status updates
  log_level: info  # Logging level (debug, info, warning, error)

# Performance monitoring
performance:
  track_slippage: true  # Track price slippage on order execution
  track_execution_time: true  # Track time to execute orders
  track_rejection_rate: true  # Track exchange rejection rate 