# Paper Trading Configuration with Real-time Optimizations

# Data Sources Configuration
data_sources:
  active_provider: public_api
  public_api:
    primary_source: coingecko
    backup_sources: [cryptocompare]
    update_interval: 10  # Seconds between API calls
    symbols: [BTC/USDT, ETH/USDT, SOL/USDT]  # Symbols to track
    realtime_timeframe: 1m
    cache_expiry: 300  # Seconds before cached data expires

# Strategy Manager Configuration
strategy_manager:
  aggregation_method: weighted_average
  min_signal_interval: 60  # Minimum seconds between signal changes (prevents excessive trading)
  stale_data_threshold: 300  # Maximum age of data in seconds before considering it stale

# Strategy Configuration
strategies:
  active_strategies: [ma_crossover, sentiment, volume]
  ma_crossover:
    enabled: true
    weight: 0.5
    parameters:
      short_window: 10
      long_window: 30
      signal_threshold: 0.2
      min_data_points: 60  # Minimum data points required for valid signals
      signal_smoothing: true  # Smooth signals to reduce noise
      cache_calculations: true  # Cache calculations for performance
  sentiment:
    enabled: true
    weight: 0.3
    parameters:
      lookback_period: 24  # hours
      sentiment_threshold: 0.2
      confidence_threshold: 0.6
      time_window: 5  # Number of recent data points to consider for trend
      trend_weight: 0.3  # Weight to give to trend vs. current sentiment (0-1)
  volume:
    enabled: true
    weight: 0.2
    parameters:
      volume_threshold: 2.0  # Threshold for relative volume to generate signals
      price_correlation_weight: 0.5  # Weight to give to price-volume correlation
      lookback_period: 20  # Number of periods to look back for volume baseline

# Risk Management Configuration
risk_management:
  max_position_size: 0.2  # Maximum position size as fraction of portfolio
  max_drawdown: 0.1  # Maximum allowed drawdown before reducing position sizes
  stop_loss: 0.05  # Stop loss as fraction of position value
  take_profit: 0.1  # Take profit as fraction of position value

# Portfolio Management Configuration
portfolio:
  initial_capital: 10000.0  # Initial capital in USD
  position_sizing_method: risk_parity  # Options: equal, risk_parity, kelly
  rebalance_threshold: 0.1  # Threshold for portfolio rebalancing

# Execution Configuration
execution:
  slippage: 0.001  # Simulated slippage as fraction of price
  commission: 0.001  # Simulated commission as fraction of trade value
  latency: 500  # Simulated execution latency in milliseconds

# Logging Configuration
logging:
  level: INFO
  file: logs/paper_trading.log
  console: true
  
# Dashboard Configuration
dashboard:
  enabled: true
  port: 8050
  refresh_interval: 5  # Seconds
