##############################################
# Security Configuration
##############################################

# API Key Management
api_keys:
  # Base storage directory. If not specified, defaults to ~/.trading_bot/keys
  # You should not normally need to change this
  storage_dir: ~/.trading_bot/keys

  # Master key settings
  master_key:
    # Iterations for key derivation
    iterations: 100000
    # NOTE: Do not store actual passwords in configuration files
    # This is only used as a fallback if no master key exists
    # In production, the user should be prompted for a password
    dev_password_hash: "sha256:1000:abc123"  # This is just a placeholder, not used in actual code

# Execution permissions
permissions:
  # Define permission groups
  groups:
    read_only:
      - read_balances
      - read_orders
      - read_trades
    trader:
      - read_balances
      - read_orders
      - read_trades
      - create_orders
      - cancel_orders
    admin:
      - read_balances
      - read_orders
      - read_trades
      - create_orders
      - cancel_orders
      - withdraw

  # Default permissions for new API keys
  default_permissions: 
    - read_balances
    - read_orders
    - read_trades

# Security logging
logging:
  # Log all security events
  enabled: true
  # Log level for security events (debug, info, warning, error, critical)
  level: info
  # Whether to mask sensitive information in logs
  mask_sensitive: true 