# Sentiment Analysis Configuration

# Main sentiment analysis settings
sentiment:
  enabled: true
  
  # NLP settings
  nlp:
    sentiment_model: "distilbert-base-uncased-finetuned-sst-2-english"
    batch_size: 16
  
  # API keys 
  apis:
    twitter:
      api_key: "${TWITTER_API_KEY}"
      api_secret: "${TWITTER_API_SECRET}"
      access_token: "${TWITTER_ACCESS_TOKEN}"
      access_secret: "${TWITTER_ACCESS_SECRET}"
    
    reddit:
      client_id: "${REDDIT_CLIENT_ID}"
      client_secret: "${REDDIT_CLIENT_SECRET}"
      user_agent: "AI-Trading-Agent/1.0"
    
    news_api:
      api_key: "${NEWS_API_KEY}"
    
    crypto_news:
      api_key: "${CRYPTO_NEWS_API_KEY}"
    
    exchange_data:
      api_key: "${EXCHANGE_DATA_API_KEY}"
    
    blockchain:
      api_key: "${BLOCKCHAIN_API_KEY}"
    
    fear_greed:
      base_url: "https://api.alternative.me/fng/"
      cache_expiry: 3600  # 1 hour in seconds
    
    blockchain_com:
      api_key: "${BLOCKCHAIN_COM_API_KEY}"
      base_url: "https://api.blockchain.info"
      cache_expiry: 900  # 15 minutes in seconds
    
    glassnode:
      api_key: "${GLASSNODE_API_KEY}"
      base_url: "https://api.glassnode.com/v1"
      cache_expiry: 900  # 15 minutes in seconds
  
  # Social Media Sentiment Agent
  social_media:
    enabled: true
    platforms:
      - Twitter
      - Reddit
    update_interval: 300  # 5 minutes
    min_confidence: 0.7
    sentiment_shift_threshold: 0.15
    contrarian_threshold: 0.8
    max_history_size: 100
  
  # News Sentiment Agent
  news:
    enabled: true
    sources:
      - CryptoNews
      - CoinDesk
      - CoinTelegraph
    update_interval: 600  # 10 minutes
    min_confidence: 0.7
    sentiment_shift_threshold: 0.15
    contrarian_threshold: 0.8
    max_history_size: 100
  
  # Market Sentiment Agent
  market:
    enabled: true
    indicators:
      - FearGreedIndex
      - LongShortRatio
    update_interval: 3600  # 1 hour
    min_confidence: 0.7
    sentiment_shift_threshold: 0.15
    contrarian_threshold: 0.8
    max_history_size: 100
  
  # Onchain Sentiment Agent
  onchain:
    enabled: true
    metrics:
      - LargeTransactions
      - ActiveAddresses
      - HashRate
      - ExchangeReserves
    update_interval: 3600  # 1 hour
    min_confidence: 0.7
    sentiment_shift_threshold: 0.15
    contrarian_threshold: 0.8
    max_history_size: 100
  
  # Sentiment Aggregator
  aggregator:
    enabled: true
    update_interval: 1800  # 30 minutes
    min_confidence: 0.7
    sentiment_shift_threshold: 0.1  # More sensitive to shifts
    source_weights:
      social_media: 0.25
      news: 0.25
      market: 0.3
      onchain: 0.2
    max_history_size: 100

# Symbols to monitor (for all sentiment agents)
symbols:
  - BTC/USDT
  - ETH/USDT
  - SOL/USDT
  - XRP/USDT
