# Trading strategies configuration

# Global settings
strategies:
  enabled: true
  enabled_strategies:
    - ma_crossover
    - sentiment
    # Add more strategies as they are implemented

  # Moving Average Crossover strategy configuration
  ma_crossover:
    enabled: true
    class_name: MovingAverageCrossoverStrategy
    module: src.strategy.ma_crossover
    
    # By default, analyze all symbols and exchanges
    # Uncomment and modify to specify specific symbols or exchanges
    # symbols:
    #   - BTC/USDT
    #   - ETH/USDT
    # exchanges:
    #   - binance
    
    # Timeframes to analyze
    timeframes:
      - 5m
      - 15m
      - 1h
      - 4h
    
    # Moving average settings
    fast_ma:
      type: EMA  # EMA or SMA
      period: 12
    
    slow_ma:
      type: EMA  # EMA or SMA
      period: 26
    
    # Signal generation settings
    min_confidence: 0.6  # Minimum confidence to generate signals (0.0 to 1.0)
    min_signal_interval: 3600  # Minimum seconds between similar signals
    
    # Position management
    use_stop_loss: true
    stop_loss_pct: 0.02  # 2%
    use_take_profit: true
    take_profit_pct: 0.05  # 5%
    
    # Event subscriptions
    subscriptions:
      - CandleDataEvent
      - TechnicalIndicatorEvent
    
    # Maximum number of signals to keep in history
    max_signal_history: 1000 

  # Sentiment-based Trading Strategy configuration
  sentiment:
    enabled: true
    class_name: SentimentStrategy
    module: src.strategy.sentiment_strategy
    
    # Trading symbols to monitor for sentiment
    symbols:
      - BTC/USDT
      - ETH/USDT
      - SOL/USDT
      - XRP/USDT
    
    # Timeframes to analyze (for candle data integration)
    timeframes:
      - 1h
      - 4h
    
    # Sentiment threshold settings
    sentiment_threshold_bullish: 0.7  # Threshold for bullish signals
    sentiment_threshold_bearish: 0.3  # Threshold for bearish signals
    min_confidence: 0.7  # Minimum confidence to generate signals
    min_signal_interval: 3600  # Minimum seconds between signals (1 hour)
    
    # Contrarian mode settings
    contrarian_mode: false  # Set to true to trade against extreme sentiment
    extreme_sentiment_threshold: 0.85  # Threshold for extreme sentiment
    
    # Source weights for sentiment aggregation
    source_weights:
      social_media: 1.0
      news: 1.0
      market: 1.0
      onchain: 1.0
      aggregator: 2.0  # Aggregator gets double weight
    
    # Position management
    use_stop_loss: true
    stop_loss_pct: 0.03  # 3%
    use_take_profit: true
    take_profit_pct: 0.06  # 6%
    
    # Event subscriptions
    subscriptions:
      - CandleDataEvent
      - SentimentEvent
    
    # Maximum number of signals to keep in history
    max_signal_history: 1000