# System Configuration
system:
  name: AI Crypto Trading System
  version: 0.1.0
  environment: development
  debug_mode: false

# Logging configuration
logging:
  level: INFO
  format: structured
  output:
    console: true
    file: false
  file_path: logs

# Execution service configuration
execution:
  retry_attempts: 3
  retry_delay: 1.0
  order_update_interval: 1.0
  cancel_orders_on_shutdown: true
  exchanges:
    mockexchange:
      type: mock
      paper_trading: true
      simulated_latency_ms: 200
      fill_probability: 0.8
      price_volatility: 0.005

# Event bus configuration
event_bus:
  max_queue_size: 1000
  worker_count: 2 