apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  template:
    spec:
      containers:
      - name: api
        env:
        - name: ENV
          value: "production"
        - name: LOG_LEVEL
          value: "DEBUG"  # More verbose logging on canary
        - name: SECURITY_AUDIT_ENABLED
          value: "true"
        - name: CANARY
          value: "true"
        - name: METRICS_TAGS
          value: "version=canary"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard
spec:
  template:
    spec:
      containers:
      - name: dashboard
        env:
        - name: REACT_APP_CANARY
          value: "true"
        - name: REACT_APP_VERSION
          value: "canary"
