apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-agent
spec:
  template:
    spec:
      containers:
      - name: trading-agent
        env:
        - name: ENV
          value: "production"
        - name: LOG_LEVEL
          value: "INFO"
        - name: USE_MOCK_DATA
          value: "false"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  template:
    spec:
      containers:
      - name: api
        env:
        - name: ENV
          value: "production"
        - name: LOG_LEVEL
          value: "INFO"
        - name: SECURITY_AUDIT_ENABLED
          value: "true"
