apiVersion: v1
kind: ConfigMap
metadata:
  name: llm-oversight-config
data:
  TRADING_LLM_PROVIDER: "openai"
  TRADING_LLM_MODEL: "gpt-4"
  # Production uses a higher level of oversight - can approve or reject decisions
  TRADING_LLM_OVERSIGHT_LEVEL: "approve"
---
# Patch to increase production resources
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-oversight
spec:
  replicas: 3  # Increase replicas for production
  template:
    spec:
      containers:
      - name: llm-oversight
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
