name: Continuous Improvement System

on:
  push:
    branches: [ main ]
    paths:
      - 'src/analysis_agents/sentiment/continuous_improvement/**'
      - 'src/dashboard/components/continuous_improvement_dashboard.py'
      - 'rust/src/sentiment/**'
      - 'src/rust_bridge/sentiment_py.py'
      - '.github/workflows/continuous-improvement.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/analysis_agents/sentiment/continuous_improvement/**'
      - 'src/dashboard/components/continuous_improvement_dashboard.py'
      - 'rust/src/sentiment/**'
      - 'src/rust_bridge/sentiment_py.py'
      - '.github/workflows/continuous-improvement.yml'
  workflow_dispatch:

jobs:
  test-python:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        
    - name: Run Python tests
      run: |
        pytest tests/analysis_agents/sentiment/continuous_improvement -v

  test-rust:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        
    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
        
    - name: Build and test Rust
      working-directory: ./rust
      run: |
        cargo test --verbose --lib sentiment::continuous_improvement
        
  build-wheels:
    needs: [test-python, test-rust]
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        
    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
        
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel maturin
        
    - name: Build wheels
      working-directory: ./rust
      run: |
        maturin build --release
        
    - name: Upload wheels
      uses: actions/upload-artifact@v3
      with:
        name: wheels
        path: ./rust/target/wheels/*.whl