name: LLM Oversight Integration CI/CD

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'ai_trading_agent/oversight/**'
      - 'frontend/src/pages/LLMOversight.tsx'
      - 'frontend/src/api/oversightClient.ts'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'ai_trading_agent/oversight/**'
      - 'frontend/src/pages/LLMOversight.tsx'
      - 'frontend/src/api/oversightClient.ts'
  workflow_dispatch:
    inputs:
      deploy_environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - production

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  PYTHON_VERSION: '3.10'
  NODE_VERSION: '16'

jobs:
  validate:
    name: Validate & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run oversight service tests
        run: |
          pytest --cov=ai_trading_agent.oversight --cov-report=xml --cov-report=term-missing tests/oversight/

  build:
    name: Build & Push Images
    needs: validate
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Oversight Service image
      - name: Build & Push Oversight Service
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile.oversight
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/oversight:${{ github.sha }},${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/oversight:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: Deploy to Environment
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    environment:
      name: ${{ github.event.inputs.deploy_environment || (github.ref == 'refs/heads/main' && 'production' || 'staging') }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "4.5.7"

      - name: Update Kubernetes resources
        env:
          DOCKER_REGISTRY: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          IMAGE_TAG: ${{ github.sha }}
          ENVIRONMENT: ${{ github.event.inputs.deploy_environment || (github.ref == 'refs/heads/main' && 'production' || 'staging') }}
        run: |
          cd kubernetes/overlays/$ENVIRONMENT
          kustomize edit set image oversight=${DOCKER_REGISTRY}/oversight:${IMAGE_TAG}
          
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.25.0'
          
      - name: Get kubeconfig
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        run: |
          mkdir -p ~/.kube
          echo "$KUBE_CONFIG" > ~/.kube/config
          chmod 600 ~/.kube/config
          
      - name: Deploy to Kubernetes
        env:
          ENVIRONMENT: ${{ github.event.inputs.deploy_environment || (github.ref == 'refs/heads/main' && 'production' || 'staging') }}
        run: |
          kubectl apply -k kubernetes/overlays/$ENVIRONMENT
          kubectl rollout status deployment/oversight -n ai-trading
          
      - name: Run oversight health check
        run: |
          sleep 30
          kubectl exec -n ai-trading deployment/oversight -- curl -f http://localhost:8080/health || exit 1
